svg:
  approachcircle:
    w: 278
    h: 278
  cursor:
    w: 160
    h: 160
  default:
    w: 318
    h: 318
    names:
      - default-0
      - default-1
      - default-2
      - default-3
      - default-4
      - default-5
      - default-6
      - default-7
      - default-8
      - default-9
  followpoint:
    w: 256
    h: 32
    names:
      - followpoint-3
      - followpoint-4
      - followpoint-5
  hit*-0:
    w: 128
    h: 128
  hit0: {}
  hit100: {}
  hit100k: {}
  hit300: {}
  hit300g: {}
  hit50: {}
  inputoverlay-key:
    w: 101
    h: 101
  reversearrow: {}
  selection-mod-*:
    w: 128
    h: 128
  sliderb0: {}
  spinner-middle2:
    w: 80
    h: 80
  spinner-top:
    w: 630
    h: 630
png:
  blank:
    names:
      - cursortrail
      - followpoint-0
      - followpoint-1
      - followpoint-2
      - followpoint-6
      - followpoint-7
      - hit300-0
      - hit300g-0
      - hit300k-0
      - hitcircleoverlay
      - hitcircle
      - inputoverlay-background
      - sliderfollowcircle
      - spinner-bottom
      - spinner-glow
      - spinner-middle
      - spinner-spin
      - star2
ini:
  skin: {}
