svg:
  approachcircle:
    w: 278
    h: 278
  cursor:
    w: 160
    h: 160
  default:
    w: 318
    h: 318
    names:
      - default-0
      - default-1
      - default-2
      - default-3
      - default-4
      - default-5
      - default-6
      - default-7
      - default-8
      - default-9
  followpoint:
    w: 256
    h: 32
    names:
      - followpoint-3
      - followpoint-4
      - followpoint-5
  hit*-0:
    w: 128
    h: 128
  hit0:
    w: 92
    h: 92
  hit100:
    w: 92
    h: 92
  hit100k:
    w: 92
    h: 92
  hit300:
    w: 92
    h: 92
  hit300g:
    w: 92
    h: 92
  hit50:
    w: 92
    h: 92
  inputoverlay-key:
    w: 101
    h: 101
  menu-button-background: {}
  reversearrow: {}
  scorebar-bg: {}
  selection-mod-*:
    w: 128
    h: 128
  sliderb0: {}
  spinner-middle2:
    w: 96
    h: 96
png:
  blank:
    names:
      - combo-0.png
      - combo-1.png
      - combo-2.png
      - combo-3.png
      - combo-4.png
      - combo-5.png
      - combo-6.png
      - combo-7.png
      - combo-8.png
      - combo-9.png
      - combo-x.png
      - count1
      - count2
      - count3
      - cursortrail
      - followpoint-0
      - followpoint-1
      - followpoint-2
      - followpoint-6
      - followpoint-7
      - go
      - hit300-0
      - hit300g-0
      - hit300k-0
      - hitcircleoverlay
      - hitcircle
      - inputoverlay-background
      - ready
      - scorebar-colour
      - scorebar-marker
      - sliderfollowcircle
      - spinner-bottom
      - spinner-glow
      - spinner-middle
      - spinner-spin
      - spinner-top
      - star2
ini:
  skin: {}
