svg:
  cursor:
    w: 160
    h: 160
  default:
    w: 318
    h: 318
    names:
      - default-0
      - default-1
      - default-2
      - default-3
      - default-4
      - default-5
      - default-6
      - default-7
      - default-8
      - default-9
  followpoint:
    w: 256
    h: 32
    names:
      - followpoint-3
      - followpoint-4
      - followpoint-5
  hit0: {}
  hit0-0:
    w: 128
    h: 128
  hit100: {}
  hit100k: {}
  hit100-0:
    w: 128
    h: 128
  hit100k-0:
    w: 128
    h: 128
  hit300: {}
  hit300g: {}
  hit50: {}
  hit50-0:
    w: 128
    h: 128
  reversearrow: {}
  sliderb0: {}
png:
  blank:
    names:
      - cursortrail
      - followpoint-0
      - followpoint-1
      - followpoint-2
      - followpoint-6
      - followpoint-7
      - hit300-0
      - hit300g-0
      - hit300k-0
      - hitcircleoverlay
      - hitcircle
      - sliderfollowcircle
      - star2
ini:
  skin: {}
