svg:
  approachcircle:
    w: 278
    h: 278
  cursor:
    w: 256
    h: 256
  cursor-smoke:
    w: 64
    h: 64
  followpoint:
    w: 256
    h: 32
    names:
      - followpoint-3
      - followpoint-4
      - followpoint-5
  hit*-0:
    w: 128
    h: 128
  hit0:
    w: 92
    h: 92
  hit100:
    w: 92
    h: 92
  hit100k:
    w: 92
    h: 92
  hit300:
    w: 92
    h: 92
  hit300g:
    w: 92
    h: 92
  hit50:
    w: 92
    h: 92
  hitcircle: {}
  hitcircleoverlay: {}
  inputoverlay-key:
    w: 101
    h: 101
  menu-button-background: {}
  reversearrow: {}
  score-*: {}
  selection-mod-*:
    w: 128
    h: 128
  sliderb0: {}
  spinner-middle2:
    w: 80
    h: 80
png:
  blank:
    names:
      - combo-0.png
      - combo-1.png
      - combo-2.png
      - combo-3.png
      - combo-4.png
      - combo-5.png
      - combo-6.png
      - combo-7.png
      - combo-8.png
      - combo-9.png
      - combo-x.png
      - count1
      - count2
      - count3
      - cursortrail
      - followpoint-0
      - followpoint-1
      - followpoint-2
      - followpoint-6
      - followpoint-7
      - go
      - hit300-0
      - hit300g-0
      - hit300k-0
      - inputoverlay-background
      - ranking-maxcombo
      - ranking-title
      - ready
      - score-x
      - scorebar-bg
      - scorebar-colour
      - scorebar-marker
      - sliderendcircle
      - sliderendcircleoverlay
      - sliderfollowcircle
      - spinner-bottom
      - spinner-glow
      - spinner-middle
      - spinner-spin
      - spinner-top
      - star2
py:
  menu-background:
    targets:
      - menu-background.jpg
  skin:
    targets:
      - skin.ini
external:
  Aesthetic:
    url: https://dl.dropboxusercontent.com/u/27093909/Aesthetic/Aesthetic_1_3_1.zip
    png:
      - button-left:
          low-res: yes
      - button-middle:
          low-res: yes
      - button-right:
          low-res: yes
      - fail-background
      - menu-back
      - pause-back
      - pause-continue
      - pause-overlay
      - pause-replay
      - pause-retry
      - play-skip
      - play-unranked
      - play-warningarrow
      - ranking-XH
      - ranking-XH-small
      - ranking-SH
      - ranking-SH-small
      - ranking-X
      - ranking-X-small
      - ranking-S
      - ranking-S-small
      - ranking-A
      - ranking-A-small
      - ranking-B
      - ranking-B-small
      - ranking-C
      - ranking-C-small
      - ranking-D
      - ranking-D-small
      - ranking-graph
      - ranking-panel
      - ranking-perfect
      - section-pass
      - section-fail
      - selection-mode
      - selection-mode-over
      - selection-mods
      - selection-mods-over
      - selection-options
      - selection-options-over
      - selection-random
      - selection-random-over
      - selection-selectoptions
      - selection-selectoptions-over
      - selection-tab:
          low-res: yes
      - sliderscorepoint
      - spinner-approachcircle
      - spinner-clear
      - spinner-rpm
