svg:
  approachcircle:
    w: 278
    h: 278
  cursor:
    w: 256
    h: 256
  cursor-smoke:
    w: 64
    h: 64
  followpoint:
    w: 256
    h: 32
    names:
      - followpoint-3
      - followpoint-4
      - followpoint-5
  hit*-0:
    w: 128
    h: 128
  hit0:
    w: 92
    h: 92
  hit100:
    w: 92
    h: 92
  hit100k:
    w: 92
    h: 92
  hit300:
    w: 92
    h: 92
  hit300g:
    w: 92
    h: 92
  hit50:
    w: 92
    h: 92
  hitcircle: {}
  hitcircleoverlay: {}
  inputoverlay-key:
    w: 101
    h: 101
  menu-button-background: {}
  reversearrow: {}
  score-*: {}
  selection-mod-*:
    w: 128
    h: 128
  sliderb0: {}
  spinner-middle2:
    w: 80
    h: 80
png:
  blank:
    names:
      - combo-0.png
      - combo-1.png
      - combo-2.png
      - combo-3.png
      - combo-4.png
      - combo-5.png
      - combo-6.png
      - combo-7.png
      - combo-8.png
      - combo-9.png
      - combo-x.png
      - count1
      - count2
      - count3
      - cursortrail
      - followpoint-0
      - followpoint-1
      - followpoint-2
      - followpoint-6
      - followpoint-7
      - go
      - hit300-0
      - hit300g-0
      - hit300k-0
      - inputoverlay-background
      - mania-stage-bottom
      - mania-stage-hint
      - ranking-maxcombo
      - ranking-title
      - ready
      - score-x
      - scorebar-bg
      - scorebar-colour
      - scorebar-marker
      - sliderendcircle
      - sliderendcircleoverlay
      - sliderfollowcircle
      - spinner-bottom
      - spinner-glow
      - spinner-middle
      - spinner-spin
      - spinner-top
      - star2
py:
  menu-background:
    targets:
      - menu-background.jpg
  skin:
    targets:
      - skin.ini
external:
  Aesthetic:
    url: https://dl.dropboxusercontent.com/u/27093909/Aesthetic/Aesthetic_1_3_1.zip
    png:
      - mania/key/blue
      - mania/key/blue-down
      - mania/key/green
      - mania/key/green-down
      - mania/key/pink
      - mania/key/pink-down
      - mania/key/purple
      - mania/key/purple-down
      - mania/key/red
      - mania/key/red-down
      - mania/key/white
      - mania/key/white-down
      - mania/key/yellow
      - mania/key/yellow-down
      - mania/note/blue
      - mania/note/green
      - mania/note/pink
      - mania/note/purple
      - mania/note/red
      - mania/note/white
      - mania/note/yellow
      - mania/sustain/blue-0
      - mania/sustain/blue-1
      - mania/sustain/green-0
      - mania/sustain/green-1
      - mania/sustain/pink-0
      - mania/sustain/pink-1
      - mania/sustain/purple-0
      - mania/sustain/purple-1
      - mania/sustain/red-0
      - mania/sustain/red-1
      - mania/sustain/white-0
      - mania/sustain/white-1
      - mania/sustain/yellow-0
      - mania/sustain/yellow-1
      - button-left:
          low-res: yes
      - button-middle:
          low-res: yes
      - button-right:
          low-res: yes
      - fail-background
      - lightingN-0
      - lightingN-1
      - lightingN-2
      - lightingN-3
      - lightingN-4
      - lightingN-5
      - lightingN-6
      - lightingN-7
      - lightingN-8
      - lightingN-9
      - lightingN-10
      - mania-hit0
      - mania-hit0-0
      - mania-hit50
      - mania-hit50-0
      - mania-hit100
      - mania-hit100-0
      - mania-hit200
      - mania-hit200-0
      - mania-hit300
      - mania-hit300-0
      - mania-hit300g
      - mania-hit300g-0
      - mania-hit300g-1
      - mania-hit300g-2
      - mania-hit300g-3
      - mania-hit300g-4
      - mania-hit300g-5
      - mania-hit300g-6
      - mania-hit300g-7
      - mania-hit300g-8
      - mania-hit300g-9
      - mania-stage-left
      - mania-stage-light:
          low-res: yes
      - mania-stage-right
      - menu-back
      - pause-back
      - pause-continue
      - pause-overlay
      - pause-replay
      - pause-retry
      - play-skip
      - play-unranked
      - play-warningarrow
      - ranking-XH
      - ranking-XH-small
      - ranking-SH
      - ranking-SH-small
      - ranking-X
      - ranking-X-small
      - ranking-S
      - ranking-S-small
      - ranking-A
      - ranking-A-small
      - ranking-B
      - ranking-B-small
      - ranking-C
      - ranking-C-small
      - ranking-D
      - ranking-D-small
      - ranking-graph
      - ranking-panel
      - ranking-perfect
      - section-pass
      - section-fail
      - selection-mode
      - selection-mode-over
      - selection-mods
      - selection-mods-over
      - selection-options
      - selection-options-over
      - selection-random
      - selection-random-over
      - selection-selectoptions
      - selection-selectoptions-over
      - selection-tab:
          low-res: yes
      - sliderscorepoint
      - spinner-approachcircle
      - spinner-clear
      - spinner-rpm
