svg:
  cursor:
    w: 84
    h: 84
    fix: True
  followpoint:
    w: 256
    h: 32
    names:
      - followpoint-3
      - followpoint-4
      - followpoint-5
  hit100:
    w: 256
    h: 256
  hit100k:
    w: 256
    h: 256
  hit100-0:
    w: 128
    h: 128
  hit100k-0:
    w: 128
    h: 128
  hit300:
    w: 256
    h: 256
  hit300g:
    w: 256
    h: 256
  hitcircle:
    w: 256
    h: 256
    fix: True
  hitcircleoverlay:
    w: 256
    h: 256
    fix: True
png:
  blank:
    names:
      - cursortrail
      - followpoint-0
      - followpoint-1
      - followpoint-2
      - followpoint-6
      - followpoint-7
      - hit300-0
      - hit300g-0
      - hit300k-0
      - star2
ini:
  skin: {}
