svg:
  cursor:
    w: 84
    h: 84
    fix: True
  default:
    w: 318
    h: 318
    names:
      - default-0
      - default-1
      - default-2
      - default-3
      - default-4
      - default-5
      - default-6
      - default-7
      - default-8
      - default-9
  followpoint:
    w: 256
    h: 32
    names:
      - followpoint-3
      - followpoint-4
      - followpoint-5
  hit0:
    w: 256
    h: 256
  hit0-0:
    w: 128
    h: 128
  hit100:
    w: 256
    h: 256
  hit100k:
    w: 256
    h: 256
  hit100-0:
    w: 128
    h: 128
  hit100k-0:
    w: 128
    h: 128
  hit300:
    w: 256
    h: 256
  hit300g:
    w: 256
    h: 256
  hit50:
    w: 256
    h: 256
  hit50-0:
    w: 128
    h: 128
  reversearrow:
    w: 256
    h: 256
  sliderb0:
    w: 256
    h: 256
png:
  blank:
    names:
      - cursortrail
      - followpoint-0
      - followpoint-1
      - followpoint-2
      - followpoint-6
      - followpoint-7
      - hit300-0
      - hit300g-0
      - hit300k-0
      - hitcircleoverlay
      - hitcircle
      - sliderfollowcircle
      - star2
ini:
  skin: {}
